### ISSUE TITLE
Onsite and Offshore Effort Hours are not being synced back from Dynamo to Informix.

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/legacy-challenge-processor#47]
eg Challenge
30175088,
30175089,
30175090
<img width="923" alt="Informix" src="https://user-images.githubusercontent.com/5771673/113002203-2dd1b100-918f-11eb-9da8-a3ede6f09ab1.png">
<img width="582" alt="Dynamo1" src="https://user-images.githubusercontent.com/5771673/113002235-3629ec00-918f-11eb-9d12-5615efe4c09c.png">
<img width="623" alt="Dynamo2" src="https://user-images.githubusercontent.com/5771673/113002266-3c1fcd00-918f-11eb-9a5e-ebf940439660.png">

**Comment by ThomasKranitsas** [comment]
It seems like this is because the values set in the `metadata` do not match the ones we use on the LCP to pull data from.

The LCP uses:

- effortHoursEstimate
- effortHoursOffshore
- effortHoursOnshore

While in your screenshots there are:

- offshoreEfforts
- onsiteEfforts

What are the correct keys to use?

cc @rootelement
